title: "Yifan Li"
url: "https://lcrucial1f.com"
baseurl: ""
description: "Undergraduate in Computer Science and Technology"
repository: "Lcrucial1f/Lcrucial1f.github.io"
author:
  name: "Yifan Li (李一帆)"
  avatar: "/images/profile.jpg"
  bio: "Qinghai University"
  location: "Xining, China"
  email: "lcrucial1f@gmail.com"
  github: "Lcrucial1f"
  googlescholar: "https://scholar.google.com/citations?user=5YwzKzEAAAAJ&hl=zh-CN"
  xiaohongshu: "https://xhslink.cn/o/4FaGSt3keJY"
include:
  - _pages
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
sass:
  sass_dir: _sass
  style: compressed
timezone: Asia/Shanghai
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
